function t228_highlight(){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
$(".t228__list_item a[href='"+url+"']").addClass("t-active");$(".t228__list_item a[href='"+url+"/']").addClass("t-active");$(".t228__list_item a[href='"+pathname+"']").addClass("t-active");$(".t228__list_item a[href='/"+pathname+"']").addClass("t-active");$(".t228__list_item a[href='"+pathname+"/']").addClass("t-active");$(".t228__list_item a[href='/"+pathname+"/']").addClass("t-active")}
function t228_setPath(){}
function t228_setWidth(recid){var window_width=$(window).width();if(window_width>980){$(".t228").each(function(){var el=$(this);var left_exist=el.find('.t228__leftcontainer').length;var left_w=el.find('.t228__leftcontainer').outerWidth(!0);var max_w=left_w;var right_exist=el.find('.t228__rightcontainer').length;var right_w=el.find('.t228__rightcontainer').outerWidth(!0);var items_align=el.attr('data-menu-items-align');if(left_w<right_w)max_w=right_w;max_w=Math.ceil(max_w);var center_w=0;el.find('.t228__centercontainer').find('li').each(function(){center_w+=$(this).outerWidth(!0)});var padd_w=40;var maincontainer_width=el.find(".t228__maincontainer").outerWidth(!0);if(maincontainer_width-max_w*2-padd_w*2>center_w+20){if(items_align=="center"||typeof items_align==="undefined"){el.find(".t228__leftside").css("min-width",max_w+"px");el.find(".t228__rightside").css("min-width",max_w+"px");el.find(".t228__list").removeClass("t228__list_hidden")}}else{el.find(".t228__leftside").css("min-width","");el.find(".t228__rightside").css("min-width","")}})}}
function t228_setBg(recid){var window_width=$(window).width();if(window_width>980){$(".t228").each(function(){var el=$(this);if(el.attr('data-bgcolor-setbyscript')=="yes"){var bgcolor=el.attr("data-bgcolor-rgba");el.css("background-color",bgcolor)}})}else{$(".t228").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-hex");el.css("background-color",bgcolor);el.attr("data-bgcolor-setbyscript","yes")})}}
function t228_appearMenu(recid){var window_width=$(window).width();if(window_width>980){$(".t228").each(function(){var el=$(this);var appearoffset=el.attr("data-appearoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if($(window).scrollTop()>=appearoffset){if(el.css('visibility')=='hidden'){el.finish();el.css("top","-50px");el.css("visibility","visible");el.animate({"opacity":"1","top":"0px"},200,function(){})}}else{el.stop();el.css("visibility","hidden")}}})}}
function t228_changebgopacitymenu(recid){var window_width=$(window).width();if(window_width>980){$(".t228").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-rgba");var bgcolor_afterscroll=el.attr("data-bgcolor-rgba-afterscroll");var bgopacityone=el.attr("data-bgopacity");var bgopacitytwo=el.attr("data-bgopacity-two");var menushadow=el.attr("data-menushadow");if(menushadow=='100'){var menushadowvalue=menushadow}else{var menushadowvalue='0.'+menushadow}
if($(window).scrollTop()>20){el.css("background-color",bgcolor_afterscroll);if(bgopacitytwo=='0'||(typeof menushadow=="undefined"&&menushadow==!1)){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}else{el.css("background-color",bgcolor);if(bgopacityone=='0.0'||(typeof menushadow=="undefined"&&menushadow==!1)){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}})}}
function t228_createMobileMenu(recid){var window_width=$(window).width();var el=$("#rec"+recid);var menu=el.find(".t228");var burger=el.find(".t228__mobile");if(980>window_width){burger.click(function(e){menu.fadeToggle(300);$(this).toggleClass("t228_opened")})}}
function t268_init(recid){var el=$("#rec"+recid);el.find(".t268__col-left").css({'height':(el.find(".t268__col-right").height()+'px')});$(window).resize(function(){el.find(".t268__col-left").css({'height':(el.find(".t268__col-right").height()+'px')})})}
var t336={};t336.initeffect=function(recid){$('#rec'+recid).find(".t336__cell").hover(function(){var sizer=$(this).find(".t336__button-container").height();$(this).find(".t336__textwrapper__content").css({'padding-bottom':(sizer+'px')});$(this).find(".t336__button-container").addClass("t336__button-container_show")},function(){$(this).find(".t336__textwrapper__content").css("padding-bottom","0");$(this).find(".t336__button-container").removeClass("t336__button-container_show")})};function t341_showCaptions(recid){var el=$("#t-carousel"+recid);var caption=el.find('.item:nth-child(1) .t-carousel__caption-inside');var captioncontainer=el.find('.t-carousel__caption__container');captioncontainer.html(caption.html());caption.css('display','none');$("#t-carousel"+recid).on('slide.bs.carousel',function(evt){var el=$("#t-carousel"+recid);var caption=el.find('.item:nth-child('+($(evt.relatedTarget).index()+1)+') .t-carousel__caption-inside');var captioncontainer=el.find('.t-carousel__caption__container');captioncontainer.html(caption.html());caption.css('display','none')})}
function t341_checkSize(recid){var el=$("#rec"+recid);var containerinside=el.find(".t-carousel__arrows__container_inside");var containeroutside=el.find(".t-carousel__arrows__container_outside");var inner=el.find(".t-carousel__inner");var arrowleft=el.find(".t-carousel__arrow_left");var arrowright=el.find(".t-carousel__arrow_right");containeroutside.css({'max-width':(arrowleft.width()+arrowright.width()+inner.width()+60+'px')});containerinside.css({'max-width':(inner.width()+'px')});var sizer=el.find('.t-carousel__height');var height=sizer.height();var width=sizer.width();if(width==0){var width=$(window).width()}
var ratio=width/height;var gallerywrapper=el.find(".t-carousel__checksize");var gallerywidth=gallerywrapper.width();if(height!=$(window).height()){gallerywrapper.css({'height':((gallerywidth/ratio)+'px')})}}
function t_slidesInit(recid){var el=$('#rec'+recid),windowWidth=$(window).width(),sliderItem=el.find('.t-slides__item'),sliderWrapper=el.find('.t-slides__items-wrapper'),sliderArrows=el.find('.t-slides__arrow_wrapper'),sliderWidth=el.find('.t-slides__container').width(),firstSlide=sliderItem.filter(':first'),lastSlide=sliderItem.filter(':last'),totalSlides=sliderItem.length,sliderDoResize,pos=1;$(window).resize(function(){if(sliderDoResize)clearTimeout(sliderDoResize);sliderDoResize=setTimeout(function(){windowWidth=$(window).width();sliderWidth=el.find('.t-slides__container').width();t_slides_setSliderWidth(recid,sliderWidth,totalSlides);slideMove()},200)});firstSlide.before(lastSlide.clone(!0).attr('data-slide-index','0'));lastSlide.after(firstSlide.clone(!0).attr('data-slide-index','4').removeClass('t-slides__item_active'));t_slides_setSliderHeight(recid);t_slides_setSliderWidth(recid,sliderWidth,totalSlides);if(980>windowWidth){sliderWrapper.css({transform:'translate3d(-'+(sliderWidth*pos)+'px, 0, 0)'})}else{sliderWrapper.css('transform','')}
el.find('.t-slides__arrow_wrapper-right').click(function(){if(!$(this).is('.t-slides__arrow-clicked')){$(this).addClass('t-slides__arrow-clicked');slideRight()}});el.find('.t-slides__arrow_wrapper-left').click(function(){if(!$(this).is('.t-slides__arrow-clicked')){$(this).addClass('t-slides__arrow-clicked');slideLeft()}});el.find('.t-slides__bullet').click(function(){pos=$(this).attr('data-slide-bullet-for');slideMove()});function slideLeft(){pos--;slideMove()}
function slideRight(){pos++;slideMove()}
function slideMove(){sliderWrapper.addClass('t-slides_animated');if(980>windowWidth){sliderWrapper.css({transform:'translate3d(-'+(sliderWidth*pos)+'px, 0, 0)'})}else{sliderWrapper.css('transform','')}
if(pos==(totalSlides+1)){pos=1}
if(pos==0){pos=totalSlides}
setTimeout(function(){sliderWrapper.removeClass('t-slides_animated');if(980>windowWidth){sliderWrapper.css({transform:'translate3d(-'+(sliderWidth*pos)+'px, 0, 0)'})}else{sliderWrapper.css('transform','')}
$('.t-slides__arrow_wrapper').removeClass('t-slides__arrow-clicked')},300);t_slides_setActiveBullet(recid,pos);t_slides_setActiveSlide(recid,pos);t_slides_setSliderHeight(recid)}
delete Hammer.defaults.cssProps.userSelect;hammer=new Hammer(el.find('.t-slides__items-wrapper')[0],{domEvents:!0,threshold:0,direction:Hammer.DIRECTION_VERTICAL});hammer.on('pan',function(event){if(980>windowWidth){var distance=event.deltaX,percentage=100/totalSlides*event.deltaX/$(window).innerWidth(),sensitivity=20;t_slides_scrollImages(recid,(sliderWidth*pos)-distance);if(event.isFinal){if(event.velocityX>1){slideLeft()}else if(event.velocityX<-1){slideRight()}else{if(percentage<=-(sensitivity/totalSlides)){slideRight()}else if(percentage>=(sensitivity/totalSlides)){slideLeft()}else{slideMove()}}}}})}
function t_slides_scrollImages(recid,distance){var el=$('#rec'+recid),value=(distance<0?"":"-")+Math.abs(distance).toString();el.find(".t-slides__items-wrapper").css("transform","translate3d("+value+"px, 0, 0)")}
function t_slides_setActiveBullet(recid,pos){var el=$('#rec'+recid),bullet=el.find('.t-slides__bullet'),bulletActive=el.find('.t-slides__bullet[data-slide-bullet-for="'+pos+'"]');bullet.removeClass('t-slides__bullet_active');bulletActive.addClass('t-slides__bullet_active')}
function t_slides_setActiveSlide(recid,pos){var el=$('#rec'+recid),slide=el.find('.t-slides__item'),slideActive=el.find('.t-slides__item[data-slide-index="'+pos+'"]');slide.removeClass('t-slides__item_active');slideActive.addClass('t-slides__item_active')}
function t_slides_setSliderWidth(recid,sliderWidth,totalSlides){var el=$('#rec'+recid);el.find('.t-slides__items-wrapper').width(sliderWidth*(totalSlides+2));el.find('.t-slides__item').width(sliderWidth)}
function t_slides_setSliderHeight(recid){var el=$('#rec'+recid);el.find('.t-slides__items-wrapper').height(el.find('.t-slides__item_active').height());el.find('.t-slides__arrow_wrapper').height(el.find('.t-slides__item_active').height())}